package com.agriwastetrade.site;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;

/**
 * Servlet implementation class ProductExploration
 */
@WebServlet("/productexplorationservlet")
public class ProductExplorationServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public ProductExplorationServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		// Ensure correct content type and encoding
		response.setContentType("text/html;charset=UTF-8");
		response.setCharacterEncoding("UTF-8");
		
		PrintWriter pw = response.getWriter();
		HashMap<String,Integer> hm  = new HashMap<>();
		
try(Connection conn = DatabaseConnectionPool.getConnectionPool() ){
			
			PreparedStatement pstmt = conn.prepareStatement("select cropid,unitsavailable from inventorydetails");
			
			ResultSet rs = pstmt.executeQuery();
			
			
			for(;rs.next();){
				hm.putIfAbsent(rs.getString("cropid"), rs.getInt("unitsavailable"));
			}
			System.out.println("hm:"+hm.get("ricehusk"));
}catch(SQLException sqle) {
	sqle.printStackTrace();
}

		// Ensure all referenced crop IDs exist in the map to prevent nulls in the embedded script
		String[] allCropIds = new String[]{
			"ricehusk","ricestraw","coffeehusk","teastalk","applepeel","applepomace","bananaleaf","bananapeel","bananapseudostem",
			"chickpeapodhusk","chickpeastalk","citruspeel","citruspulp","coffeepulp","coffeesilverskin","corncob","cornhusk","cornstover",
			"cottonseedhull","cottonstalk","groundnuthaulms","groundnutshells","mangopeel","mangoseed","mustardseedcake","mustardstalk",
			"onionouterskin","onionpeel","pigeonpeapodshells","potatopeel","rottentomato","soybeancake","soybeanhulls",
			"soybeanstraw","sugarcaneleaves","sugarcanetops","sugarcanetrash","teadust","teapruning","tomatoseed","tomatoskin",
			"turmericleaves","tumericrizhomepeel","turmericrizhomepeel","wheathusk","wheatstraw"
		};
		for (String id : allCropIds) { hm.putIfAbsent(id, 0); }
		
		pw.print("<!DOCTYPE html>"
				+ "<html lang=\"en\">"
				+ "<head>"
				+ "<meta charset=\"utf-8\">"
				+ "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
				+ "<title>AgriWaste Trading — Biomass Products</title>"
				+ "<style>"
				+ "  :root{"
				+ "    --bg:#0f1318; --surface:#ffffff; --ink:#0e1926; --muted:#5b6677; --line:#e6eaf0;"
				+ "    --accent:#0f8b8d; --accent-2:#16537e; --chip:#eef8f6; --badge:#f2f6ff;"
				+ "    --ok:#1b5e20; --warn:#8a6d1e; --danger:#b3261e;"
				+ "  }"
				+ "  *{box-sizing:border-box}"
				+ "  html,body{height:100%}"
				+ "  body{ margin:0; font-family:Inter,system-ui,Segoe UI,Roboto,Arial,sans-serif; color:#1b2430; background:#f5f7fb; }"
				+ ""
				+ "  /* App bar */"
				+ "  .appbar{ position:sticky; top:0; z-index:10; background:#0f1318; color:#eaf2ff; border-bottom:1px solid rgba(255,255,255,0.08); }"
				+ "  .appbar-inner{ width:min(1200px,94vw); margin:auto; display:flex; align-items:center; justify-content:space-between; padding:12px 4px; }"
				+ "  .brand{ display:flex; align-items:center; gap:12px; }"
				+ "  .logo{ width:34px; height:34px; border-radius:6px; background:linear-gradient(135deg,#0f8b8d,#16537e); color:#0d1a1f; font-weight:800; display:flex; align-items:center; justify-content:center; box-shadow:0 6px 18px rgba(0,0,0,0.35); }"
				+ "  .brand h1{ margin:0; font-size:1.02rem; letter-spacing:.2px; color:#e7eefc; }"
				+ "  .audience{ font-size:.86rem; color:#b7c3d6; }"
				+ "  .cart-button{ position:relative; background:#12a39f; border:none; color:#fff; font-weight:700; padding:8px 12px; border-radius:10px; cursor:pointer; }"
				+ "  .cart-count{ position:absolute; top:-7px; right:-7px; background:#ff6b6b; color:#fff; font-size:.75rem; border-radius:999px; padding:2px 6px; }"
				+ ""
				+ "  /* Filters panel */"
				+ "  .container{ width:min(1200px,94vw); margin:18px auto 30px; }"
				+ "  .panel{ background:#ffffff; border:1px solid var(--line); border-radius:14px; padding:14px; box-shadow:0 6px 18px rgba(0,0,0,0.08); }"
				+ "  .filters{ display:grid; grid-template-columns:1.4fr 1fr 1fr 1fr 0.9fr; gap:10px; }"
				+ "  .filters input,.filters select{ width:100%; padding:10px 12px; border-radius:10px; border:1px solid #d8dde6; background:#fff; color:var(--ink); outline:none; }"
				+ "  .chips{ margin-top:10px; display:flex; gap:8px; flex-wrap:wrap; }"
				+ "  .chip{ font-size:0.86rem; background:#f5f7fb; border:1px solid #e3e8f1; padding:6px 10px; border-radius:999px; color:#425067; }"
				+ ""
				+ "  /* Toolbar */"
				+ "  .toolbar{ margin:12px 0; display:flex; gap:10px; flex-wrap:wrap; align-items:center; }"
				+ "  .btn{ appearance:none; border:1px solid #d5dce6; background:#ffffff; color:#203040; padding:8px 12px; border-radius:10px; cursor:pointer; font-weight:600; }"
				+ "  .btn.primary{ background:linear-gradient(135deg,#0f8b8d,#16537e); color:#fff; border:none; }"
				+ "  .btn.ghost{ background:#f8fbff; border:1px dashed #cfd8e6; }"
				+ "  #count{ margin-left:auto; color:#5d6a7f; }"
				+ ""
				+ "  /* Grid + Cards */"
				+ "  .grid{ margin-top:16px; display:grid; gap:16px; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); }"
				+ "  .card{ background:var(--surface); color:var(--ink); border:1px solid var(--line); border-radius:14px; overflow:hidden; box-shadow:0 8px 20px rgba(0,0,0,0.06); display:flex; flex-direction:column; transition:transform .15s ease, box-shadow .15s ease; }"
				+ "  .card:hover{ transform: translateY(-2px); box-shadow:0 12px 26px rgba(0,0,0,0.10); }"
				+ "  .image-wrap{ position:relative; width:100%; padding-top:56%; background:#f2f4f8; overflow:hidden; }"
				+ "  .image-wrap img{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; }"
				+ "  .card-head{ padding:14px 14px 0; display:flex; align-items:center; justify-content:space-between; gap:10px; }"
				+ "  .title{ padding:8px 14px 0; font-weight:700; font-size:1.02rem; text-transform:capitalize; }"
				+ "  .meta{ padding:8px 14px 14px; display:flex; gap:10px; align-items:center; flex-wrap:wrap; }"
				+ "  .unit{ color:#415161; background:#f6f8fb; border:1px solid #e7ebf2; border-radius:8px; padding:6px 10px; }"
				+ "  .availability{ background:#eef7f0; color:#175d1e; border:1px solid #cfe6d3; padding:6px 10px; border-radius:8px; font-weight:600; }"
				+ "  .out{ background:#fff6e6; color:#8a6d1e; border:1px solid #f0e0aa; }"
				+ "  .price{ background:#f2f6ff; color:#1c3f86; border:1px solid #d8e3ff; padding:6px 10px; border-radius:8px; font-weight:700; }"
				+ "  .region-badge{ background:#f7f9fc; color:#415161; border:1px solid #e6ecf5; padding:6px 10px; border-radius:8px; }"
				+ "  .tag{ font-weight:700; font-size:.78rem; padding:6px 10px; border-radius:999px; background:#eef5ff; color:#2c3a66; border:1px solid #d9e2ff; }"
				+ "  .actions{ margin-top:auto; padding:12px 14px; display:flex; justify-content:space-between; align-items:center; border-top:1px dashed #e9ecf1; gap:8px; }"
				+ "  .qty-inline{ display:flex; align-items:center; gap:6px; }"
				+ "  .qty-inline input{ width:64px; padding:6px 8px; border:1px solid #d5dce6; border-radius:8px; }"
				+ ""
				+ "  .empty{ text-align:center; color:#738198; padding:30px; border:1px dashed #d7dee9; border-radius:12px; background:#fff; }"
				+ ""
				+ "  /* Modal */"
				+ "  .modal-backdrop{ position:fixed; inset:0; background:rgba(7,12,18,0.55); display:none; align-items:center; justify-content:center; z-index:40; }"
				+ "  .modal{ width:min(900px, 96vw); background:#fff; color:#18202a; border-radius:14px; overflow:hidden; box-shadow:0 20px 50px rgba(0,0,0,0.35); }"
				+ "  .modal .mhead{ padding:14px 16px; border-bottom:1px solid #e9ecf1; display:flex; align-items:center; justify-content:space-between; }"
				+ "  .modal .mbody{ padding:16px; }"
				+ "  .modal .mfooter{ padding:12px 16px; border-top:1px solid #e9ecf1; display:flex; justify-content:space-between; gap:8px; align-items:center; }"
				+ "  .close-x{ cursor:pointer; border:none; background:transparent; font-size:20px; line-height:1; }"
				+ "  .farmer-list{ margin-top:8px; border:1px solid #e9ecf1; border-radius:10px; background:#f9fbfd; }"
				+ "  .farmer-row{ display:grid; grid-template-columns: 1fr auto auto auto; gap:10px; padding:8px 10px; border-bottom:1px dashed #e3e7ee; align-items:center; }"
				+ "  .farmer-row:last-child{ border-bottom:none; }"
				+ "  .pill{ padding:4px 8px; border-radius:999px; background:#eef2ff; color:#384a98; border:1px solid #d9e1ff; font-size:.82rem; }"
				+ "  .price-pill{ background:#eef7ff; color:#1c3f86; border-color:#cfe0ff; font-weight:700; }"
				+ "  .minq{ background:#f6fbf3; color:#1a5a1b; border-color:#cfe6d3; }"
				+ ""
				+ "  .modal-flex{ display:grid; grid-template-columns: 1.2fr 1.8fr; gap:14px; }"
				+ "  .modal-img{ width:100%; aspect-ratio:16/10; object-fit:cover; border-radius:10px; border:1px solid #e9ecf1; }"
				+ ""
				+ "  /* Cart Drawer */"
				+ "  .cart-drawer{ position:fixed; top:0; right:0; width:min(420px, 96vw); height:100%; background:#fff; color:#18202a; box-shadow:-10px 0 30px rgba(0,0,0,0.25); transform:translateX(100%); transition:transform .25s ease; z-index:60; display:flex; flex-direction:column; }"
				+ "  .cart-drawer.open{ transform:translateX(0); }"
				+ "  .cart-head{ padding:14px 16px; border-bottom:1px solid #e9ecf1; display:flex; justify-content:space-between; align-items:center; }"
				+ "  .cart-body{ padding:12px 16px; overflow:auto; flex:1; }"
				+ "  .cart-item{ display:grid; grid-template-columns:auto 1fr auto; gap:10px; align-items:center; padding:10px 0; border-bottom:1px dashed #e9ecf1; }"
				+ "  .cart-item img{ width:56px; height:56px; object-fit:cover; border-radius:8px; border:1px solid #e9ecf1; }"
				+ "  .cart-item .ci-title{ font-weight:700; }"
				+ "  .cart-item .ci-meta{ color:#5d6a7f; font-size:.86rem; }"
				+ "  .cart-item .ci-qty{ display:flex; align-items:center; gap:6px; }"
				+ "  .cart-foot{ border-top:1px solid #e9ecf1; padding:12px 16px; display:flex; flex-direction:column; gap:8px; }"
				+ "  .row-between{ display:flex; justify-content:space-between; }"
				+ "</style>"
				+ "</head>"
				+ "<body>"
				+ "  <div class=\"appbar\">"
				+ "    <div class=\"appbar-inner\">"
				+ "      <div class=\"brand\">"
				+ "        <div class=\"logo\">AT</div>"
				+ "        <h1>Biomass & AgriWaste — Products</h1>"
				+ "      </div>"
				+ "      <div style=\"display:flex;align-items:center;gap:10px;\">"
				+ "        <div class=\"audience\">For industrial buyers, compost/fertilizer makers, and farmers</div>"
				+ "        <button id=\"open-cart\" class=\"cart-button\">Cart <span id=\"cart-count\" class=\"cart-count\" style=\"display:none;\">0</span></button>"
				+ "      </div>"
				+ "    </div>"
				+ "  </div>"
				+ ""
				+ "  <div class=\"container\">"
				+ "    <!-- Filters -->"
				+ "    <div class=\"panel\">"
				+ "      <div class=\"filters\">"
				+ "        <input id=\"search\" type=\"search\" placeholder=\"Search (e.g., rice husk, wheat straw, coffee husk)…\" aria-label=\"Search products\">"
				+ "        <select id=\"category\" aria-label=\"Filter by category\">"
				+ "          <option value=\"\">All categories</option>"
				+ "          <option value=\"cerealcrop\">Cereal crop</option>"
				+ "          <option value=\"fruitcrop\">Fruit crop</option>"
				+ "          <option value=\"vegetablecrop\">Vegetable crop</option>"
				+ "          <option value=\"oilseedcrop\">Oilseed crop</option>"
				+ "          <option value=\"fibercrop\">Fiber crop</option>"
				+ "          <option value=\"sugarcrop\">Sugar crop</option>"
				+ "          <option value=\"spices\">Spices</option>"
				+ "          <option value=\"pulsewaste\">Pulse waste</option>"
				+ "        </select>"
				+ "        <select id=\"region\" aria-label=\"Preferred region\">"
				+ "          <option value=\"\">All regions</option>"
				+ "        </select>"
				+ "        <select id=\"availability\" aria-label=\"Availability\">"
				+ "          <option value=\"\">Any availability</option>"
				+ "          <option value=\"in\">In stock (>0)</option>"
				+ "          <option value=\"out\">Out of stock (=0)</option>"
				+ "        </select>"
				+ "        <select id=\"sort\" aria-label=\"Sort\">"
				+ "          <option value=\"price-asc\">Price: Low→High</option>"
				+ "          <option value=\"price-desc\">Price: High→Low</option>"
				+ "          <option value=\"name-asc\">Name: A→Z</option>"
				+ "          <option value=\"name-desc\">Name: Z→A</option>"
				+ "          <option value=\"qty-desc\">Quantity: High→Low</option>"
				+ "          <option value=\"qty-asc\">Quantity: Low→High</option>"
				+ "          <option value=\"cat-asc\">Category</option>"
				+ "        </select>"
				+ "      </div>"
				+ "      <div class=\"chips\" id=\"summary\"></div>"
				+ "    </div>"
				+ ""
				+ "    <div class=\"toolbar\">"
				+ "      <button class=\"btn ghost\" id=\"reset\">Reset filters</button>"
				+ "      <button class=\"btn\" id=\"toggle-zero\">Hide zero-stock</button>"
				+ "      <span id=\"count\"></span>"
				+ "    </div>"
				+ ""
				+ "    <div id=\"grid\" class=\"grid\"></div>"
				+ "    <div id=\"empty\" class=\"empty\" style=\"display:none;\">No products match the filters.</div>"
				+ "  </div>"
				+ ""
				+ "  <!-- Product details modal -->"
				+ "  <div id=\"modal-backdrop\" class=\"modal-backdrop\" role=\"dialog\" aria-modal=\"true\" aria-hidden=\"true\">"
				+ "    <div class=\"modal\">"
				+ "      <div class=\"mhead\">"
				+ "        <div style=\"display:flex;align-items:center;gap:10px;\">"
				+ "          <strong id=\"m-title\" style=\"text-transform:capitalize;\">Product</strong>"
				+ "        </div>"
				+ "        <button class=\"close-x\" id=\"m-close\" aria-label=\"Close\">×</button>"
				+ "      </div>"
				+ "      <div class=\"mbody\">"
				+ "        <div class=\"modal-flex\">"
				+ "          <img id=\"m-img\" class=\"modal-img\" alt=\"Product image\">"
				+ "          <div>"
				+ "            <div style=\"display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px;\">"
				+ "              <span id=\"m-tag\" class=\"tag\">Category</span>"
				+ "              <span id=\"m-qty\" class=\"availability\">0 available</span>"
				+ "              <span id=\"m-unit\" class=\"pill\">Unit: kg</span>"
				+ "              <span id=\"m-cropid\" class=\"pill\">ID: …</span>"
				+ "              <span id=\"m-price\" class=\"price\">₹—</span>"
				+ "            </div>"
				+ ""
				+ "            <div style=\"display:flex; gap:8px; align-items:center; margin:8px 0 14px;\">"
				+ "              <label for=\"m-region\" style=\"font-weight:600;color:#2a3952;\">Select region:</label>"
				+ "              <select id=\"m-region\" style=\"padding:8px 10px; border-radius:10px; border:1px solid #d8dde6;\"></select>"
				+ "            </div>"
				+ ""
				+ "            <div class=\"qty-inline\" style=\"margin:8px 0 14px;\">"
				+ "              <label for=\"m-qty-input\" style=\"font-weight:600;color:#2a3952;\">Quantity:</label>"
				+ "              <input id=\"m-qty-input\" type=\"number\" min=\"1\" value=\"1\">"
				+ "              <span id=\"m-unit-inline\" class=\"pill\">kg</span>"
				+ "            </div>"
				+ ""
				+ "            <div style=\"display:flex; gap:8px; flex-wrap:wrap;\">"
				+ "              <button class=\"btn\" id=\"modal-add-cart\">Add to Cart</button>"
				+ "              <button class=\"btn primary\" id=\"modal-buy-now\">Buy Now</button>"
				+ "            </div>"
				+ "          </div>"
				+ "        </div>"
				+ ""
				+ "        <h4 style=\"margin:1rem 0 .4rem;\">Farmers supplying this product</h4>"
				+ "        <div id=\"farmer-list\" class=\"farmer-list\">"
				+ "          <div style=\"padding:8px 10px;color:#6b7785;\">Fetching farmers…</div>"
				+ "        </div>"
				+ "      </div>"
				+ "      <div class=\"mfooter\">"
				+ "        <div style=\"color:#5d6a7f;\">Price range is mostly demand-based from multiple farmers</div>"
				+ "        <div>"
				+ "          <button class=\"btn\" id=\"contact-btn\">Contact us</button>"
				+ "          <button class=\"btn primary\" id=\"enquire-btn\">Enquire availability</button>"
				+ "        </div>"
				+ "      </div>"
				+ "    </div>"
				+ "  </div>"
				+ ""
				+ "  <!-- Cart Drawer -->"
				+ "  <div id=\"cart\" class=\"cart-drawer\" aria-hidden=\"true\">"
				+ "    <div class=\"cart-head\">"
				+ "      <strong>Cart</strong>"
				+ "      <button id=\"close-cart\" class=\"close-x\" aria-label=\"Close\">×</button>"
				+ "    </div>"
				+ "    <div id=\"cart-body\" class=\"cart-body\">"
				+ "      <div style=\"color:#6b7785;\">Cart is empty.</div>"
				+ "    </div>"
				+ "    <div class=\"cart-foot\">"
				+ "      <div class=\"row-between\"><span>Subtotal</span><strong id=\"subtotal\">₹0</strong></div>"
				+ "      <div class=\"row-between\" style=\"color:#5d6a7f;\"><span>Taxes & Shipping</span><span>Calculated at checkout</span></div>"
				+ "      <button id=\"checkout\" class=\"btn primary\">Checkout</button>"
				+ "    </div>"
				+ "  </div>"
				+ ""
				+ "<script>"
				+ "/* ========== Configuration & Data Hooks ========== */"
				+ "const PRODUCTS_URL = \"\";"
				+ "const FARMERS_URL  = \"\";"
				+ "const REGIONS_URL  = \"\";"
				+ ""
				+ "// Fallback images by category"
				+ "const PLACEHOLDER_BY_CAT = {"
				+ "  cerealcrop: \"https://images.unsplash.com/photo-1560807707-8cc77767d783?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  fruitcrop: \"https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  vegetablecrop: \"https://images.unsplash.com/photo-1506806732259-39c2d0268443?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  oilseedcrop: \"https://images.unsplash.com/photo-1495197359483-d092478c170a?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  fibercrop: \"https://images.unsplash.com/photo-1486575008575-27670acb58ac?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  sugarcrop: \"https://images.unsplash.com/photo-1621881523537-6f2c5132f551?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  spices: \"https://images.unsplash.com/photo-1505577058444-a3dab90d4253?q=80&w=1200&auto=format&fit=crop\"," 
				+ "  pulsewaste: \"https://images.unsplash.com/photo-1518843875459-f738682238a6?q=80&w=1200&auto=format&fit=crop\""
				+ "};"
				+ ""
				+ "const EMBEDDED_DATA = {"
				+ "  products:"
				+ "  ["
				+ "    {cropid:\"ricehusk\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("ricehusk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"ricestraw\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("ricestraw")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"coffeehusk\", categoryid:\"spices\", unitsavailable:"+hm.get("coffeehusk")+",  unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"teastalk\", categoryid:\"spices\", unitsavailable:"+hm.get("teastalk")+",  unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"applepeel\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("applepeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"applepomace\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("applepomace")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"bananaleaf\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("bananaleaf")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"bananapeel\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("bananapeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"bananapseudostem\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("bananapseudostem")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"chickpeapodhusk\", categoryid:\"pulsewaste\", unitsavailable:"+hm.get("chickpeapodhusk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"chickpeastalk\", categoryid:\"pulsewaste\", unitsavailable:"+hm.get("chickpeastalk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"citruspeel\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("citruspeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"citruspulp\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("citruspulp")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"coffeepulp\", categoryid:\"spices\", unitsavailable:"+hm.get("coffeepulp")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"coffeesilverskin\", categoryid:\"spices\", unitsavailable:"+hm.get("coffeesilverskin")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"corncob\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("corncob")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"cornhusk\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("cornhusk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"cornstover\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("cornstover")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"cottonseedhull\", categoryid:\"fibercrop\", unitsavailable:"+hm.get("cottonseedhull")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"cottonstalk\", categoryid:\"fibercrop\", unitsavailable:"+hm.get("cottonstalk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"groundnuthaulms\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("groundnuthaulms")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"groundnutshells\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("groundnutshells")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"mangopeel\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("mangopeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"mangoseed\", categoryid:\"fruitcrop\", unitsavailable:"+hm.get("mangoseed")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"mustardseedcake\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("mustardseedcake")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"mustardstalk\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("mustardstalk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"onionouterskin\", categoryid:\"vegetablecrop\", unitsavailable:"+hm.get("onionouterskin")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"onionpeel\", categoryid:\"vegetablecrop\", unitsavailable:"+hm.get("onionpeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"pigeonpeapodshells\", categoryid:\"pulsewaste\", unitsavailable:"+hm.get("pigeonpeapodshells")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"potatopeel\", categoryid:\"vegetablecrop\", unitsavailable:"+hm.get("potatopeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"rottentomato\", categoryid:\"vegetablecrop\", unitsavailable:"+hm.get("rottentomato")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"soybeancake\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("soybeancake")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"soybeanhulls\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("soybeanhulls")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"soybeanstraw\", categoryid:\"oilseedcrop\", unitsavailable:"+hm.get("soybeanstraw")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"sugarcaneleaves\", categoryid:\"sugarcrop\", unitsavailable:"+hm.get("sugarcaneleaves")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"sugarcanetops\", categoryid:\"sugarcrop\", unitsavailable:"+hm.get("sugarcanetops")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"sugarcanetrash\", categoryid:\"sugarcrop\", unitsavailable:"+hm.get("sugarcanetrash")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"teadust\", categoryid:\"spices\", unitsavailable:"+hm.get("teadust")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"teapruning\", categoryid:\"spices\", unitsavailable:"+hm.get("teapruning")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"tomatoseed\", categoryid:\"vegetablecrop\", unitsavailable:"+hm.get("tomatoseed")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"tomatoskin\", categoryid:\"vegetablecrop\", unitsavailable:"+hm.get("tomatoskin")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"turmericleaves\", categoryid:\"spices\", unitsavailable:"+hm.get("turmericleaves")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"tumericrizhomepeel\", categoryid:\"spices\", unitsavailable:"+hm.get("turmericrizhomepeel")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"wheathusk\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("wheathusk")+", unittype:\"kg\", imageUrl:\"\"},"
				+ "    {cropid:\"wheatstraw\", categoryid:\"cerealcrop\", unitsavailable:"+hm.get("wheatstraw")+", unittype:\"kg\", imageUrl:\"\"}"
				+ "  ],"
				+ "  farmersByCrop: {"
				+ "    ricehusk:"
				+ "    ["
				+ "      {farmerName:\"Ravi Kumar\", region:\"Guntur, Andhra Pradesh\", pricePerUnit:9.5,  minOrderQty:500},"
				+ "      {farmerName:\"A. Reddy\",   region:\"Karimnagar, Telangana\", pricePerUnit:10.2, minOrderQty:300},"
				+ "      {farmerName:\"S. Patel\",   region:\"Nashik, Maharashtra\",    pricePerUnit:11.0, minOrderQty:800}"
				+ "    ],"
				+ "    ricestraw:"
				+ "    ["
				+ "      {farmerName:\"B. Singh\",   region:\"Indore, Madhya Pradesh\", pricePerUnit:6.0,  minOrderQty:1000},"
				+ "      {farmerName:\"K. Sharma\",  region:\"Varanasi, Uttar Pradesh\",pricePerUnit:5.5,  minOrderQty:800}"
				+ "    ],"
				+ "    coffeehusk:"
				+ "    ["
				+ "      {farmerName:\"J. Gowda\",   region:\"Belagavi, Karnataka\",     pricePerUnit:18.0, minOrderQty:200},"
				+ "      {farmerName:\"R. Iyer\",    region:\"Erode, Tamil Nadu\",       pricePerUnit:17.2, minOrderQty:350}"
				+ "    ],"
				+ "    teastalk:"
				+ "    ["
				+ "      {farmerName:\"P. Das\",     region:\"Bardhaman, West Bengal\",  pricePerUnit:14.5, minOrderQty:250}"
				+ "    ],"
				+ "    sugarcanebagasse:"
				+ "    ["
				+ "      {farmerName:\"M. Rao\",     region:\"Guntur, Andhra Pradesh\",  pricePerUnit:7.8,  minOrderQty:700},"
				+ "      {farmerName:\"L. Naik\",    region:\"Belagavi, Karnataka\",     pricePerUnit:8.2,  minOrderQty:600}"
				+ "    ]"
				+ "  },"
				+ "  regions: ["
				+ "    \"Guntur, Andhra Pradesh\",\"Karimnagar, Telangana\",\"Belagavi, Karnataka\",\"Erode, Tamil Nadu\",\"Nashik, Maharashtra\"," 
				+ "    \"Varanasi, Uttar Pradesh\",\"Indore, Madhya Pradesh\",\"Bardhaman, West Bengal\""
				+ "  ]"
				+ "};"
				+ ""
				+ "/* ========== Utilities ========== */"
				+ "const fmt = new Intl.NumberFormat('en-IN', {maximumFractionDigits:2});"
				+ "function priceRange(list){"
				+ "  const prices = (list||[]).map(x=>Number(x.pricePerUnit)).filter(n=>!isNaN(n));"
				+ "  if(!prices.length) return null;"
				+ "  return {min: Math.min(...prices), max: Math.max(...prices)};"
				+ "}"
				+ "function niceName(id){ return id.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').replace(/([a-z])([a-z]+)/gi,(m)=>m).replace(/[ ]+/g,' ').trim().replace(/\\b([a-z])/g, s=>s.toUpperCase()); }"
				+ "function categoryLabel(id){"
				+ "  const map = {cerealcrop:'Cereal crop',fruitcrop:'Fruit crop',vegetablecrop:'Vegetable crop',oilseedcrop:'Oilseed crop',fibercrop:'Fiber crop',sugarcrop:'Sugar crop',spices:'Spices',pulsewaste:'Pulse waste'};"
				+ "  return map[id] || id;"
				+ "}"
				+ "function escapeHtml(s){ return String(s).replace(/[&<>\"']/g,(m)=>({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#039;' }[m])); }"
				+ "function imgFor(p){ return p.imageUrl && p.imageUrl.trim() ? p.imageUrl : (PLACEHOLDER_BY_CAT[p.categoryid] || PLACEHOLDER_BY_CAT.cerealcrop); }"
				+ ""
				+ "/* ========== State ========== */"
				+ "let PRODUCTS = [];");
}
}